spring.application.name=smha SMS

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.main.banner-mode=off
logging.level.org.springframework=info
#logging.level.root=warn
file.upload-directory=/home/afzalalhaia/upload/smsAtik



#=======================
# Liquibase
#========================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml
spring.liquibase.default-schema=public











